import { LegalPage } from "../../components/LegalPage";

export const metadata = { title: "Privacy notice", description: "Privacy information for Feynman Education users and school contacts." };

const sections = [
  { id: "scope", title: "Who this notice is for", content: <><p>This notice explains how Feynman Education handles information from users of the retrieval application and from people who contact us about a school pilot or licence.</p><p>For school-managed pupil and staff information, the school will normally decide why the data is used and Feynman Education operates the service on the school’s instructions. Schools should provide their own privacy information to pupils, parents and staff where required.</p></> },
  { id: "information", title: "Information we handle", content: <><ul><li>Account details such as name, email, role and school membership.</li><li>Class membership, curriculum topics, teacher-created questions and assignments.</li><li>Pupil answers, marks, feedback, appeals, activity and progress information.</li><li>Technical and operational information such as request identifiers, success, latency and usage totals.</li><li>School-enquiry information submitted through the pricing page.</li></ul></> },
  { id: "purpose", title: "Why it is used", content: <><p>Information is used to authenticate users, provide retrieval practice, mark and schedule questions, show progress to authorised staff, support marking review, maintain and secure the service, understand costs and respond to school enquiries.</p><p>Public school enquiries are handled to respond to the requested pilot or licence discussion. School-managed information is used to deliver the service under the applicable school arrangement.</p></> },
  { id: "ai", title: "AI processing", content: <><p>Some written answers and staff tools use Anthropic. The relevant question, marking context and answer text may be sent for processing. Routine marking prompts are designed not to include pupil names, email addresses or internal user identifiers. Anonymised wrong-answer text and private teacher question-bank content may be processed by staff AI functions.</p><p>See the <a href="/trust#data-flow">trust centre data-flow section</a> for more detail.</p></> },
  { id: "sharing", title: "Who supports the service", content: <><p>The current core providers are Vercel, Supabase and Anthropic. They support hosting, authentication, database, server functions and AI processing. Information may also be disclosed where required by law or to protect users and the service.</p></> },
  { id: "local-storage", title: "Browser storage and telemetry", content: <><p>The application uses browser storage where necessary to maintain sign-in, remember onboarding choices and connect an anonymous revision-booklet session with a later account journey. It also records limited funnel events and operational usage so the service can be improved and monitored.</p></> },
  { id: "retention", title: "Retention", content: <><p>Data is kept for as long as it is needed to operate the account, preserve spaced-practice history, meet the relevant school arrangement or handle an enquiry. School-specific retention and deletion should be agreed during procurement. Enquiry information can be removed when it is no longer needed.</p></> },
  { id: "rights", title: "Questions and rights", content: <><p>Depending on the context, people may have rights to access, correct, erase or restrict use of their personal information, and to object or complain. For a school-managed account, contact the school first because it will usually be best placed to identify the record and decide the request.</p><p>For service or enquiry questions, email <a href="mailto:schools@feynmaneducation.com">schools@feynmaneducation.com</a>. You may also complain to the UK Information Commissioner’s Office.</p></> },
];

export default function PrivacyPage() {
  return <LegalPage eyebrow="Legal information" title="Privacy notice" intro="How account, school, learning and enquiry information is used in the current Feynman Education service." sections={sections} />;
}

