import { Icon } from "../../components/Icon";
import { LegalPage } from "../../components/LegalPage";

export const metadata = { title: "Trust centre", description: "How Feynman Education approaches AI processing, school data, security, access and accessibility." };

const sections = [
  { id: "summary", title: "At a glance", content: <><p>Feynman Education is a retrieval-practice application for schools. It stores the information needed to operate classes, deliver questions, mark answers and show progress to authorised users.</p><div className="legal-note">This page describes the current product and is intended to support an informed school review. It does not claim an external security or accessibility certification.</div></> },
  { id: "data-flow", title: "AI and data flow", content: <><p>The current AI marking provider is Anthropic. When an open written answer needs AI assessment, the service may send the question text, model answer or marking points, relevant marking guidance and the pupil-written answer to Anthropic. The routine marking prompt is designed not to include the pupil’s name, email or internal user identifier.</p><p>Some staff AI tools process class misconceptions or generate questions. Those operations may send anonymised wrong-answer text and private teacher question-bank content to Anthropic. The application records provider, model, request and response identifiers, operation, latency and success information for operational usage monitoring.</p><p>Multiple-choice, exact-match, numerical and previously accepted equivalent answers can be handled without a new AI request. This reduces external processing as well as cost.</p></> },
  { id: "teacher-control", title: "Teacher control", content: <><p>AI output is not treated as unchallengeable. Pupils can flag a decision, teachers can review the original answer and marking context, and authorised staff can uphold or overturn the mark. A marking-quality dashboard shows review and agreement information.</p><p>Schools control their own class setup, content selection, assignments and teacher-created questions. Feynman should support professional judgement rather than replace it.</p></> },
  { id: "security", title: "Security and access", content: <><p>Authentication is provided through Supabase Auth. Application records are protected using authenticated requests, role-aware application checks and database row-level access policies. Teacher, head-of-department and moderator capabilities are separated.</p><ul><li>Production traffic is served over HTTPS.</li><li>Secrets used by server-side functions are not exposed in the browser application.</li><li>Administrative actions require an authenticated, authorised account.</li><li>Usage and request identifiers support investigation without being used as pupil-facing identifiers.</li></ul><p>To report a suspected vulnerability or incident, email <a href="mailto:schools@feynmaneducation.com">schools@feynmaneducation.com</a> with “Security” in the subject line.</p></> },
  { id: "subprocessors", title: "Service providers", content: <><p>The current core service stack includes Vercel for web hosting, Supabase for authentication, database and server functions, and Anthropic for the AI operations described above. Provider and processing terms can change as the service develops; schools should request the current subprocessor and transfer information during procurement.</p></> },
  { id: "retention", title: "Retention and deletion", content: <><p>The product retains account, class, question and response records so that pupils can continue spaced practice and staff can review progress. A single universal retention period is not represented here because school requirements may differ.</p><p>Before production adoption, a school can request a documented offboarding, deletion and retention schedule appropriate to its role and policies. Account and class-management controls support removal of users and memberships, while database deletion requests should be coordinated to preserve referential and audit integrity.</p></> },
  { id: "accessibility", title: "Accessibility", content: <><p>The interface is being developed toward WCAG 2.2 AA practices, including keyboard-operable controls, visible focus, meaningful labels, responsive layouts, reduced-motion support and readable contrast. It has not yet been independently audited, so we do not claim formal conformance.</p><p>Please report a barrier, including the page, device and assistive technology used, to <a href="mailto:schools@feynmaneducation.com">schools@feynmaneducation.com</a>.</p></> },
  { id: "procurement", title: "School procurement", content: <><p>Schools can use this centre as a starting point and request the supporting information required by their own process, including data-processing terms, subprocessor details, security questions and deletion arrangements.</p><p><a className="public-button" href="mailto:schools@feynmaneducation.com?subject=Feynman%20procurement%20questions">Contact us about procurement <Icon name="arrow" size={14}/></a></p></> },
];

export default function TrustPage() {
  return <LegalPage eyebrow="For schools and trusts" title="Trust centre" intro="A plain-English view of what the product processes, when AI is involved, where teachers remain in control and which questions a school should settle before adoption." sections={sections} />;
}

